#!/bin/sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle.
# Standard wrapper script - regenerate the matching gradle-wrapper.jar via
# `gradle wrapper` or by opening this project in Android Studio (it will be
# downloaded automatically on first sync).
##############################################################################
DEFAULT_JVM_OPTS=""
APP_HOME=$(cd "$(dirname "$0")" && pwd)
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
exec java $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
